package winston.gameLibrary;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;


/*
import java.sql.Blob;
*/

/**
 * Created by 4th3ist on 5/2/2016.
 */

public class GameSQLiteDatabaseHelper extends SQLiteOpenHelper {
    //Define DB: name
    public static final int DATABASE_VERSION = 1;
    public static final String DATABASE_NAME = "game_library.db";
    public static final String GAME_TBL_NAME = "Game_Table";

    //DB Columns
    public static final String COL_ID = "_id";
    public static final String COL_NAME = "name";
    public static final String COL_GENRE = "genre";
    public static final String COL_RELEASE = "release";
    public static final String COL_BLURB = "blurb";

    public static final String[] GAME_COLUMNS =
            {COL_ID, COL_NAME, COL_GENRE, COL_RELEASE, COL_BLURB};

    private static final String CREATE_GAME_TABLE
            = "CREATE TABLE "+ GAME_TBL_NAME +
         "("+COL_ID+ " INTEGER PRIMARY KEY AUTOINCREMENT, "
            +COL_NAME+" TEXT, "
            +COL_GENRE+" TEXT, "
            +COL_RELEASE+" TEXT, "
            +COL_BLURB+" TEXT )";

    private static GameSQLiteDatabaseHelper mInstance;

    public static GameSQLiteDatabaseHelper getInstance(Context context){
        if(mInstance==null){
            mInstance = new GameSQLiteDatabaseHelper(context);
        }
        return mInstance;
    }
    //04/05-shc-ver
    public GameSQLiteDatabaseHelper(Context context){
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
//        setForcedUpgrade();
    }

    @Override
    //04/05-shc-ver
    // Create the games table when the database is created
    public void onCreate (SQLiteDatabase db){
        db.execSQL(CREATE_GAME_TABLE);
        setDefaultData(db);
    }

    // Delete old DB, creates new DB
    public void onUpgrade (SQLiteDatabase db, int oldVersion, int newVersion){
        //04/05-shc-ver
        // public final String SQL_DROP_GAMELIB_TABLE = "DROP TABLE IF EXISTS gameLibrary";
        db.execSQL("DROP TABLE IF EXISTS" + GAME_TBL_NAME);
        this.onCreate(db);
    }//end onUpgrade


//-------------BEGIN HARDCODED #overkill DB SEED-------------\\
//-------------!!WARNING!!: UNFOLD AT OWN RISK---------------\\
    public void setDefaultData(SQLiteDatabase db){
/* Database _id
1-AoEIII | 2-AvP2 | 3-BF3 | 4-Blacklight | 5-BL | 6-BL2 | 7-Bulletstorm | 8-BurnoutRevenge | 9-BurnoutParadise | 10-Carcassonne | 11-Catan | 12-CoH | 13-CoV |
14-Civ4| 15-Civ5 | 16-Civ-BE | 17-C&C3-TW | 18-C&C-G-ZH | 19-C&C-RA2 | 20-C&C-RA3 | 21-Crackdown | 22-Defiance | 23-DeusEx | 24-D2-LoD | 25-D3 | 26-Dragon'sDogma |
27-Fable2 | 28-Fable3 | 29-FFX | 30-FFX2 | 31-FFXIV | 32-Gears1 | 33-Gears2 | 34-Gears3 | 35-GW | 36-GW2 |
37-Halo3 | 38-Halo3-ODST | 39-Halo4 | 40-HaloReach | 41-Halo5 |
42-HGL | 43-HoMM3 | 44-HoMM4 | 45-HoMM5-TotE | 46-HoMM6 | 47-HoMM7 | 48-HotS | 49-KF | 50-KoAR |
51-ME1 | 52-ME2 | 53-ME3 | 54-MiddleEarth-SoM | 55-Payday2 |
56-PQ-CotW | 57-PQ2 | 58-Q3A | 59-Recettear | 60-SimCity | 61-sC4 | 62-SPAZ | 63-SC2 | 64-TabulaRasa | 65-Terraria | 66-LotR-TBfME1 |  67-LotR-TBfME2 | 68-TSW |
69-TheDivision | 70-TooHuman | 71-TL1 | 72-TL2 | 73-TA | 74-UT2k4 | 75-UT3 |76-Wc3-RoC | 77-Wc3-TFT | 78-Warframe |
79-WH40k-DoW-DC | 80-WH40k-DoW-SS | 81-WH40k-DoW2 | 82-WH40k-DoW2-CR | 83-WH40k-DoW2-Retrib | 84-WH40k-SM |
85-WoW | 86-WormsArmageddon | 87-XmenLegends2-RoA | 88-XCOM-EU | 89-XCOM2
*/
    /*  //TEMPLATE#
        ContentValues
        values = new ContentValues();
        values.put(COL_NAME, "");
        values.put(COL_GENRE, "");
        values.put(COL_RELEASE, "");
        values.put(COL_BLURB, "");
        db.insert(GAME_TBL_NAME, null, values);*/

        ContentValues
            values = new ContentValues(); values.put(COL_NAME, "Age of Empires III (PC)");	values.put(COL_GENRE, "Strategy, RTS"); values.put(COL_RELEASE, "2005-10-18");	values.put(COL_BLURB, "Age of Empires III will offer gamers the next level of realism, with advanced battle physics and unparalleled visual detail. The new game picks up where Age of Empires II: Age of Kings left off, placing gamers in the position of a European power determined to explore, colonize and conquer the New World. This time period features stunning scenes, from towering European cathedrals to courageous tribes of Native Americans, and spectacular combat with Industrial Age units like rifled infantry, cavalry and tall ships bristling with cannons. Age of Empires III will once again demonstrate Ensemble Studios' reputation for excellence and innovation in the real-time strategy (RTS) genre. The game will set a new standard for visual quality and amaze players with detail never before seen in an RTS. Age of Empires III will excite strategy gamers with new game-play elements, including the concept of a 'Home City,' new civilizations, units, technologies and an immersive new single-player campaign that will span three generations.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Aliens Versus Predator 2 (PC)");	values.put(COL_GENRE, "Action, Shooter, Sci-fi, FPS"); values.put(COL_RELEASE, "2001-10-31");	values.put(COL_BLURB, "Go to the Planet LV1201, where three diverse and bloodthirsty species battle for survival. The action is heart-stopping. You can choose to play as Alien, Predator, or Marine as you use your physical prowess, killer instincts, or superior firepower to stay alive.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Battlefield 3 (Xbox 360)");	values.put(COL_GENRE, "Action Shooter, Modern, FPS"); values.put(COL_RELEASE, "2011-10-15");	values.put(COL_BLURB, "Battlefield 3 leaps ahead of the competition with the power of Frostbite 2, the next installment of DICE's cutting-edge game engine. This state-of-the-art technology is the foundation on which Battlefield 3 is built, delivering superior visual quality, a grand sense of scale, massive destruction, dynamic audio and incredibly lifelike character animations. As bullets whiz by, walls crumble, and explosions throw you to the ground, the battlefield feels more alive and interactive than ever before. In Battlefield 3, players step into the role of the elite U.S. Marines where they will experience heart-pounding single player missions and competitive multiplayer actions ranging across diverse locations from around the globe including Europe, Middle-East and North America.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Blacklight Retribution (PC)");	values.put(COL_GENRE, "Action, MMO, Shooter, Sci-fi, FPS"); values.put(COL_RELEASE, "2012-02-28");	values.put(COL_BLURB, "Blacklight Retribution is a fast paced, adrenaline pumping first person shooter based in a futuristic urban warzone. FPS enthusiasts are provided with a massive arsenal of weaponry and gear, ranging from bleeding edge side arms to massive mechanized hardsuits. Customize your weapons and gear for the perfect load out and earn credits in-game to change the tide of battle by deploying flame throwers, automatic grenade launchers and even airstrikes!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Borderlands (Xbox 360)");	values.put(COL_GENRE, "Action, RPG, Sci-fi, FPS"); values.put(COL_RELEASE, "2009-10-20");	values.put(COL_BLURB, "A sci-fi / action RPG from acclaimed developer Gearbox, Borderlands combines the best in first-person action with player customization and vehicular combat for incredible layers of gameplay depth. The game features a groundbreaking content generation system allowing for near-endless variety in missions, environments, enemies, weapons, item drops and character customization. Borderlands allows for multiple players to share the same game experience simultaneously online in co-op gameplay. Players can freely join or leave each other's games at anytime, or choose to play in the full single-player mode. The game also boasts lifelike character animations, impressive real-time physics, and customizable vehicles.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Borderlands 2 (Xbox 360)");	values.put(COL_GENRE, "Action, RPG, Sci-fi, FPS"); values.put(COL_RELEASE, "2012-09-17");	values.put(COL_BLURB, "Borderlands 2 is the epic sequel to the ultimate four-player Role-Playing Shooter loot fest. Combining invention and evolution, Borderlands 2 features all new characters, skills, environments, enemies, weapons and equipment, which come together in an ambitiously crafted story. Players will reveal secrets, and escalate mysteries of the Borderlands universe as they adventure across the unexplored new areas of Pandora.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Bulletstorm (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, Sci-fi, FPS"); values.put(COL_RELEASE, "2011-02-22");	values.put(COL_BLURB, "Set in a futuristic utopia, an elite peacekeeping force thwarts the rumblings of civil war. But deception within the ranks has caused two members of the most feared unit, Dead Echo, to strike out on their own. Now washed-up mercenaries turned space pirates, Grayson Hunt and Ishi Sato's latest quest for a quick buck goes south. Stumbling upon their ex-commander's warship, the Ulysses, Grayson engages this behemoth head-on. Outmanned and outgunned, his only option is to ram the Ulysses in a suicidal bid at redemption. Narrowly surviving a crash landing and stranded on the abandoned paradise planet of Stygia, Grayson and Ishi find themselves surrounded by hordes of mutants and flesh-eating gangs. They survive on two objectives: get off the planet alive and exact revenge on the man who sent them there. Taking the role of Grayson Hunt, wield over-the-top combat moves and some of the most uniquely innovative weapons ever seen in a first-person shooter that all feed into the distinct skillshot system for unprecedented levels of frantic gameplay. Unleash the Bulletstorm!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Burnout Revenge (Xbox 360)");	values.put(COL_GENRE, "Racing"); values.put(COL_RELEASE, "2006-03-07");	values.put(COL_BLURB, "Burnout: Revenge is not about winning. It's not about riding on dubs or gaudy neon lights. It's about being the fastest, most dangerous racer on the road. Fight dirty or go down in flames - the only rule is complete automotive anarchy. All-new cars in three classes (race, muscle and crash) accentuate different play styles and power ups, physically transforming as they become more powerful Tracks spanning three continents and inspired by real-world cities - from Detroit to Rome to Tokyo Online Play - Take Burnout Revenge online for 6 player online action on Xbox Live");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Burnout Paradise (Xbox 360)");	values.put(COL_GENRE, "Racing"); values.put(COL_RELEASE, "2007-09-11");	values.put(COL_BLURB, "The fifth entry in the gonzo racing series, Burnout Paradise gives players license to wreak havoc in Paradise City, the ultimate racing battleground, with a massive infrastructure of traffic-heavy roads to abuse. Gone is the need to jump in and out of menus and aimlessly search for fun like many open world games; in Burnout 7, every inch of the world is built to deliver heart-stopping Burnout-style gameplay. Every intersection is a potential crash junction and every alleyway is an opportunity to rack up moving violations. Feel the adrenaline course through your veins as you take to the road for the first time in Paradise City, where the action is all around you. Explore the city, discover events, and look for the best opportunities to crash, jump and pull signature takedowns. In Burnout Paradise yo''re given the keys to the city, but it's up to you to earn the keys to the meanest and most dangerous cars on the street, and earn your Burnout license.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Carcassonne (XBLA)");	values.put(COL_GENRE, "Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2007-06-27");	values.put(COL_BLURB, "Master strategy in the medieval world! In the classic board game Carcassonne, the medieval countryside thrives as you and your opponents place tiles and complete towns, roads, and farms while competing to amass the most points. Own the largest towns, longest roads, and biggest farms. Build your world at the expense of your opponents. * Full game implementation: Carcassonne features the complete 72 tiles from the original board game, all rule sets, and the 12 additional tiles found in the Rivers 1 Expansion Set. * Challenge your friends: Multiplayer capability allows for up to five players on Xbox LIVE, or four players on one Xbox 360â„¢ console. * Easy to learn and play: A helpful step-by-step tutorial will teach you the game in minutes. * Special A.I. settings: Special A.I. settings will challenge any skill level.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Catan (XBLA)");	values.put(COL_GENRE, "Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2004-12-17");	values.put(COL_BLURB, "Catan, based on the best-selling board game 'Settlers of Catan,' places you in the role of a colonist on a newly discovered imaginary island. Through strategy and trading, vie for control with other players over the territory and resources of this uncharted wilderness. Compete online with your friends from around the world, or go up against a computer personality. Features include an all-new 3-D 'Living World' environment and robust computer gameplay to challenge all skill levelsâ€”even the experts! Catan is addictive fun for all ages, taking just minutes to learn and a lifetime to master! * New version: Enjoy the Xbox LIVE Arcade version of the world's most popular Eurogame, 'Settlers of Catan' with an all-new 3-D 'Living World' board. * Difficulty levels: Play against historical personalities including Alexander, Cleopatra, and Tokugawaâ€”a challenge to all skill levels, even experts! Also included is a 'Learn As You Play' tutorial. * House rules: Use popular house rules including Friendly Robber and Friendly Resources. * Dice roll options: Choose from Randomized or Dice Deck with re-shuffling options. * Multiplayer interaction: Taunt your opponents with engaging animations and emotes.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "City of Heroes (PC)");	values.put(COL_GENRE, "MMO, RPG");	values.put(COL_RELEASE, "2004-04-28");	values.put(COL_BLURB, "City of Heroes is a new kind of massive multiplayer online game. If you've ever wanted to defend your city from evildoers as a mighty superhero, now's your chance. Choose your powers, join a team and go online for tremendous role-playing action! You'll also have to watch your Fame meter -- the higher your reputation gets, the more bonuses and rewards you'll get. Team up with other players online, to form new superhero groups and take down the bad guys more effectively");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "City of Villains (PC)");	values.put(COL_GENRE, "MMO, RPG");	values.put(COL_RELEASE, "2005-10-31");	values.put(COL_BLURB, "City of Villains is the standalone sequel to critically acclaimed MMORPG City of Heroes. Using a staggering assortment of new powers, abilities, and customization options, players can now experience sinister game play from the other side of the mask. With diabolical craft and guile, players forge new super-powered villain characters in an attempt to dominate the world. Heroes and authorities of Paragon City will do all in their power to thwart these evil plans of destruction. It will take a supreme effort for true domination.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Civilization IV (PC)");	values.put(COL_GENRE, "Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2005-10-24");	values.put(COL_BLURB, "With over 6 million units sold and unprecedented critical acclaim from fans and press around the world, Sid Meier's Civilization is recognized as one of the greatest PC game franchises of all-time. Now, Sid Meier and Firaxis Games will take this incredibly fun and addictive game to new heights by adding new ways to play and win, new tools to manage and expand your civilization, all-new easy to use mod capabilities and intense multiplayer modes and options. Civilization IV will come to life like never before in a beautifully detailed, living 3D world that will elevate the gameplay experience to a whole new level. Civilization IV has already been heralded as one of the top ten games of 2005, and a must-have for gamers around the globe!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Civilization V (PC)");	values.put(COL_GENRE, "Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2010-09-21");	values.put(COL_BLURB, "In Civilization V, players strive to become Ruler of the World by establishing and leading a civilization from the dawn of man into the space age, waging war, conducting diplomacy, discovering new technologies, going head-to-head with some of history's greatest leaders and building the most powerful empire the world has ever known.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Civilization Beyond Earth (PC)");	values.put(COL_GENRE, "Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2014-10-24");	values.put(COL_BLURB, "Sid Meier's Civilization: Beyond Earth is a new science-fiction-themed entry into the award-winning Civilization series. Set in the future, global events have destabilized the world leading to a collapse of modern society, a new world order and an uncertain future for humanity. As the human race struggles to recover, the re-developed nations focus their resources on deep space travel to chart a new beginning for mankind. As part of an expedition sent to find a home beyond Earth, you will write the next chapter for humanity as you lead your people into a new frontier and create a new civilization in space. Explore and colonize an alien planet, research new technologies, amass mighty armies, build incredible Wonders and shape the face of your new world. As you embark on your journey you must make critical decisions. From your choice of sponsor and the make-up of your colony, to the ultimate path you choose for your civilization, every decision opens up new possibilities.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Command and Conquer 3 Tiberium Wars (PC)");	values.put(COL_GENRE, "Strategy, Sci-fi, RTS");	values.put(COL_RELEASE, "2007-03-26");	values.put(COL_BLURB, "Command & Conquer 3 Tiberium Wars takes you forward in the Command & Conquer universe, where a brief peace ends in a storm of war. The year is 2047 and a massive nuclear fireball explodes in the night sky, marking the dramatic beginning of the Third Tiberium War. With the corrupt substance Tiberium blanketing most of the Earth, the infamous Kane is back to lead his Brotherhood of Nod in a massive assault on the Global Defense Initiative (GDI) and the few remaining livable Blue Zones left on the planet. Only you can stop him. Welcome back, Commander. Build flying battleships, wield the power of terrifying Ion Storms & combine units to form powerful never-before-seen super-units Multiple online game modes, all-new multiplayer maps, and a fully featured content editor.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Command and Conquer Generals Zero Hour (PC)");	values.put(COL_GENRE, "Strategy, Modern, RTS");	values.put(COL_RELEASE, "2003-09-22");	values.put(COL_BLURB, "Command and Conquer: Generals  Zero Hour is the expansion pack for the game Command & Conquer: Generals. Zero Hour added several new abilities to each side, and a new mode of play called Generals' Challenge. Zero Hour also contains 3 new campaigns of five missions each, one for each side, with their chronological order being USA first, GLA second, and China last. Unlike the previous campaigns, which were noted by Command and Conquer fans for not having full motion video cinematic sequences during mission briefing, the Zero Hour campaigns return to that Command and Conquer tradition, each showing a live-action video of a news reporter of the respective side giving details about the situation behind the current mission. The plot behind the Zero Hour campaigns picks up where it left off at the end of the previous campaigns.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Command and Conquer Red Alert 2 (PC)");	values.put(COL_GENRE, "Strategy, RTS");	values.put(COL_RELEASE, "2001-10-10");	values.put(COL_BLURB, "Sticking firm to the old 'if it ain't broke' philosophy, Westwood Studios conjures up memories of the original Command & Conquer games with Command & Conquer: Red Alert 2. The game is set just a few years after the events of the original Red Alert, and opens with a surprise Soviet invasion of the U.S. mainland. Playing as the startled Americans, you must cobble together a resistance and beat the invaders back into the sea. Playing as the Soviets, you must quickly establish control of your new domain, wiping out all opposition you meet. Red Alert 2 is very similar to the original Red Alert, with some visual enhancements and gameplay improvements brought in from the recent Command & Conquer: Tiberian Sun game. You still lead a small group of infantry and armored units in most missions and you still have to assemble a base of operations in order to accomplish just about anything. This time around, however, you'll have a slew of new units to build and command in the field--most of which are pretty slick. The American Prism Tank, for example, can take out numerous enemy units with a single, branching attack. On the Soviet side, Tesla Troopers and Psychics help make ground troops a formidable asset.<p> Another nice addition to the game is the ability to garrison troops inside buildings. Because much of the fighting is on city streets, it helps to give your troops some cover from time to time. Also, there are a number of special buildings that provide unique advantages once occupied by engineer units. The airport allows you to call in air strikes, for example, while oil derricks provide a resource boost for your war machine. Multiplayer support is still the calling card of this series, and fans of past games will not be disappointed by Red Alert 2's multiplayer options. The basic free-for-all mode that the original Red Alert made famous is still intact, but the alternative multiplayer modes are the real treat. In Unholy Alliance, players get access to both American and Soviet tech trees, while the naval war variant starts each player off on a small island. In addition, the game includes special cooperative campaigns.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Command and Conquer Red Alert 3 (PC)");	values.put(COL_GENRE, "Strategy, RTS");	values.put(COL_RELEASE, "2008-10-27");	values.put(COL_BLURB, "Return to the Red Alert continuity of the esteemed Command & Conquer RTS franchise in this full-fledged series sequel. Red Alert 3 breaks new ground in the RTS genre, featuring a fully co-operative campaign while bringing back the series' light-hearted style and classic, action-oriented gameplay. In Red Alert 3, the desperate leadership of a doomed Soviet Union travels back in time to change history and restore the glory of Mother Russia. The time travel mission goes awry, creating an alternate timeline where technology has followed an entirely different evolution, a new superpower has been thrust on to the world stage, and World War III is raging. The Empire of the Rising Sun has risen in the East, making World War III a three-way struggle between the Soviets, the Allies, and the Empire with armies fielding wacky and wonderful weapons and technologies like Tesla coils, heavily armed War Blimps, teleportation, armored bears, intelligent dolphins, floating island fortresses, and transforming tanks.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Crackdown (Xbox 360)");	values.put(COL_GENRE, "Action, Third-person, TPS");	values.put(COL_RELEASE, "2007-02-20");	values.put(COL_BLURB, "Crackdown pushes the action-driving hybrid genre into the next generation with the first ever truly 3-D playground. Gamers will enforce justice by any means necessary in Pacific City, a crime-ridden urban center built to encourage the exploration of the full width, depth and height of the city. Coupled with highly innovative co-op gameplay -- a genre first -- and an interactive world where nearly anything can be used as a weapon, gamers will be able to create a volatile cocktail of judicial oppression as they clean up the streets. More than 100 licensed tracks, spanning a wide range of styles and genres.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Defiance (Xbox 360)");	values.put(COL_GENRE, "MMO RPG, Sci-fi, Third-person, TPS");	values.put(COL_RELEASE, "2013-04-02");	values.put(COL_BLURB, "Join a futuristic open-world shooter where thousands of players scour a transformed Earth competing for alien technology. Hunt alone or with others as you improve your skills and unlock powerful modern and alien weapons that will help you survive and take charge during huge online co-op battles and fierce multiplayer conflicts.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Deus Ex (PC)");	values.put(COL_GENRE, "RPG, Sci-fi, FPS");	values.put(COL_RELEASE, "2000-06-23");	values.put(COL_BLURB, "Deus Ex is the first in a series mixing action and RPG play by Warren Spector, the creator of Ultima Underworld and System Shock. The world is in chaos. Terrorists roam the streets. The reemergence of an ancient secret society bent on world domination. Playing as rookie UNATCO agent J.C. Denton, you will use your nanotech-enhanced body and mind to fight the enemy in this Unreal engine-based action/RPG hybrid. Denton improves his skills, receives additional bionic enhancements and plays with many sorts of equipment as the game develops. The intriguing story takes you from New York to Hong Kong, from Paris to secret labs, for over seventy hours of exploration. A software development kit has even been released so people can develop their own adventures.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Diablo 2 Lord of Destruction (PC)");	values.put(COL_GENRE, "Action, Fantasy, RPG, Isometric");	values.put(COL_RELEASE, "2001-06-25");	values.put(COL_BLURB, "Since the Beginning of Time the forces of Order and Chaos have been engaged in an eternal struggle to decide the fate of all Creation. That struggle has now come to the Mortal Realm... And neither Man, Demon, nor Angel will be left unscathed... In the Diablo II Expansion Set, you will return to follow the path of Baal, the last of the Prime Evils, into the Barbarian Highlands of the north. Traveling with hordes of demonic minions, Baal intends to corrupt the powerful Worldstone that protects the whole of the mortal plane from the forces of Hell. You will face a new series of quests and challenges to prevent the vile minions of the underworld from destroying the world of Sanctuary.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Diablo 3 (PC)");	values.put(COL_GENRE, "Action, Fantasy, RPG, Isometric");	values.put(COL_RELEASE, "2012-05-15");	values.put(COL_BLURB, "Two decades have passed since the demonic lords, Diablo, Mephisto, and Baal, set out across the world of Sanctuary on a vicious rampage, twisting humanity to their unholy will. Yet for those who battled the Prime Evils, the memory fades slowly. When Deckard Cain returns to the ruins of Tristram Cathedral seeking clues to defeat new stirrings of evil, a fiery harbinger of doom falls from the heavens, striking the very ground where Diablo once entered the world. This fire from the sky reawakens ancient evils and calls the heroes of Sanctuary to defend the mortal world against the rising powers of the Burning Hells once again.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Dragon's Dogma (Xbox 360)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2012-05-22");	values.put(COL_BLURB, "A new legend is born in this epic open-world adventure. Take on the role of the Arisen, a legendary hero, in a land haunted by a fearsome, all-powerful dragon. As you fight your way to protect your homeland, you'll gain companions, make enemies, and find yourself tied to an even deeper mystery...");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Fable 2 (Xbox 360)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2008-10-21");	values.put(COL_BLURB, "Set 500 years after the original game, Fable II offers even more choices and features, while building on the core gameplay theme of Fable where every choice continually defines who you become, allowing you to truly live the life you choose. Fable II expands upon the scope and depth of the original by adding incredible new features and creating a wider, more complex kingdom of limitless choices and consequences. Players will have the option to play as a man or woman, get married, have children, and live a life of their own design -- all leading to different destinies.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Fable 3 (Xbox 360)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2010-10-26");	values.put(COL_BLURB, "In Fable III, the latest installment of the critically acclaimed Xbox 360 exclusive franchise, fans new and returning will now embark on an epic adventure, where the race for the crown is only the beginning of your spectacular journey. Five decades have passed since the events of Fable II, and Albion has matured into an industrial revolution, but the fate of the kingdom is at peril. You will be called upon to rally and fight alongside your people, ascend to the seat of power, and experience the realities of defending your throne. Along your journey, the choices you make will change the world around you, for the greater good or your own personal gain. Who will you become? A rebel without a cause, the tyrant you rebelled against, or the greatest ruler to ever live?");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Final Fantasy X (PS3)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2001-12-18");	values.put(COL_BLURB, "Following the exploits of the Summoner Yuna and her guardians as they battle an evil immortal enemy known as Sin, Final Fantasy X is the first title in the franchise to appear on the PlayStation 2. It's also the first game in Squaresoft's popular RPG series to feature voiceovers in addition to written text. Character expressiveness also reaches new heights with the aid of Squaresoft's 'Facial Motion System', adding subtle facial expressions to characters in real-time. New side-quests include the underwater sport of Blitzball, and a monster battle arena as well as a redesigned fighting system that mixes classic Final Fantasy elements with a new 'Sphere Grid' system.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Final Fantasy X2 (PS3)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2014-03-18");	values.put(COL_BLURB, "It is a year after the dark deity Sin was beaten, in Final Fantasy X. The people of Spira are at peace and have embraced former enemies. But powerful mystic spheres begin popping up and old rivalries come with them. Exciting new gaming enhancements - unique job classes, mission based non-linear gameplay, quicker battle system and stunning graphics. An all-female cast with new abilities, like switching job classes in the middle of a battle. Dynamic movements and Active Time Battle (ATB) quickens the pace of enemy encounters.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Final Fantasy XIV A Realm Reborn (PC)");	values.put(COL_GENRE, "Fantasy, MMO, RPG");	values.put(COL_RELEASE, "2013-08-27");	values.put(COL_BLURB, "'FINAL FANTASY XIV: A Realm Reborn' is a massively multiplayer online role-playing game (MMORPG) for Windows  PC and PlayStation 3 that invites you to explore the realm of Eorzea with friends from around the world. Form a party and adventure with a multitude of players from across the globe. Forge friendships, mount chocobos, and board airships as you and your companions create your own unique stories in Eorzea. Set out alone or enlist the aid of friends as you undertake epic quests, battle familiar FINAL FANTASY monsters, and acquire unique abilities and equipment. All the classic elements from the series that you have come to know and love are waiting! Embark on the adventure of a lifetime to help reforge the fate of Eorzea! A Land embraced by Gods and forged by Heroes. Seeking control of this realm and its abundant crystal resources, the Garlean Empire sends forth a massive host on a campaign to conquer its southern neighbor. Driven by madness, the commander of the invading forces silently plots to tear the moon from the heavens and hurl it down upon the land. The people of the realm soon learn of this foul scheme, and join their hands in prayer in an eleventh-hour attempt to entreat the aid of the gods, only to see their endeavors fail. From within the moon emerges Bahamut, an ancient terror seething with rage fueled by countless generations of imprisonment. Sensing the tug of Fate, a powerful magus channels the last of his strength to send Eorzea's heroes into a temporal rift. There they wait, untouched by the flames of destruction, until they are needed again. Those heroes are you, and the hour of awakening is now. Come and witness a realm reborn.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Gears of War (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, Third-person, TPS");	values.put(COL_RELEASE, "2006-11-21");	values.put(COL_BLURB, "Gears of War thrusts gamers into a deep and harrowing story of humankind's epic battle for survival against the Locust Horde, a nightmarish race of creatures that surface from the bowels of the planet. Players live and breathe the role of Marcus Fenix. A disgraced former war hero, Marcus, seeks personal redemption as he leads his fire team against an onslaught of merciless warrior fiends. Gamers immerse themselves in an experience so intensely emotional and gut-wrenching that playing will be like controlling a blockbuster action movie. Control Marcus Fenix and his fire team as they pit advanced human technology against the overwhelming and horrific Locust Horde. Gears of War unites next-generation technology with classic, emotional storytelling and a revolutionary tactical combat system, engrossing the gamer in a horrifying epic story of war and survival. Unreal Engine 3 technology pushes high-definition visual designs and brings out the smallest details in the largest battle.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Gears of War 2 (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, Third-person, TPS");	values.put(COL_RELEASE, "2008-11-07");	values.put(COL_BLURB, "The gears of war continue to turn as Marcus Fenix and his squad of Cogs go back into action in the sequel to Microsoft and developer Epic Games' blockbuster action title. Gears of War 2 continues the story of Marcus Fenix and Delta Squad, locked in an increasingly desperate battle against the nightmarish Locust Horde for the survival of humanity. The game promises to be an epic saga of survival, loss, and retribution. Just as Gears of War set the standard for high-definition visuals, Gears of War 2 raises the bar even further with the amazing technological advances of Unreal Engine 3, delivering a bigger, badder, and more intense experience as the story continues.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Gears of War 3 (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, Third-person, TPS");	values.put(COL_RELEASE, "2011-09-20");	values.put(COL_BLURB, "Gears of War 3 is the spectacular conclusion to one of the most memorable and celebrated sagas in video games. Developed by Epic Games exclusively for Xbox 360, Gears of War 3 plunges you into a harrowing tale of hope, survival, and brotherhood. In Gears of War 3, fight on as Marcus Fenix, the grizzled war hero and leader of Delta Squad. Eighteen months after the fall of the last human city, the war against the Locust rages on. Meanwhile, deep beneath the surface, a fearsome new threat is infecting the planet from within. With survivors scattered and civilization in ruins, time is running out for Marcus and his comrades as they fight to save the human race. The Gears of War series is one of the most popular franchises in Xbox history, with more than 12 million games sold worldwide.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Guild Wars (PC)");	values.put(COL_GENRE, "Fantasy, MMO, RPG");	values.put(COL_RELEASE, "2005-04-28");	values.put(COL_BLURB, "Guild Wars is a new kind of MMORPG experience. It eliminates the less exciting aspects of world-map play by using a mission-based design, while still keeping the features that make massive online role-players great. Make new allies in towns or outposts, form a party, and then go tackle a quest together. Your party always has its own unique copy of the quest map, so camping, kill-stealing, and long lines to complete quests are all things of the past. As you play out your quest, you have an unprecedented level of freedom: Your magic can build bridges and open up new pathways, or it can burn down forests and villages. Best of all, you'll never meet new players only to discover that you can't play with them or compete against them because their characters are on a different server than yours -- in Guild Wars, all characters live in one seamless world.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Guild Wars 2 (PC)");	values.put(COL_GENRE, "Fantasy, MMO, RPG");	values.put(COL_RELEASE, "2012-08-28");	values.put(COL_BLURB, "Guild Wars 2 takes place roughly 250 years after the end of Eye of the North, Guild Wars's first and last official expansion pack. 'The general theme is one where humanity, dominant in Guild Wars, is besieged on all sides and they're worried that their day is coming to an end.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Halo 3 (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, FPS");	values.put(COL_RELEASE, "2007-09-25");	values.put(COL_BLURB, "Halo 3 is the third game in the Halo Trilogy and the thrilling conclusion to the events begun in Halo: Combat Evolved. Master Chief returns to finish the fight, bringing the epic conflict between the Covenant, the Flood, and the entire human race to a dramatic, pulse-pounding climax. The Covenant occupation of Earth has uncovered a massive and ancient object beneath the African sands - an object whose secrets have yet to be revealed. Earth's forces are battered and beaten. The Master Chief's AI companion Cortana is still trapped in the clutches of the Gravemind - a horrifying Flood intelligence, and a civil war is raging in the heart of the Covenant. It's all been building to this -- a desperate, final war that leads to a soul-shattering climax of epic proportions. Take control of Master Chief to defeat the Covenant and destroy the Flood as a measure to prevent the annihilation of the human race. Online multiplayer - Halo 3 builds upon the unique party-based social multiplayer experience from Halo 2 with new weapons, vehicles, maps, gametypes, and added customizability!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Halo 3 ODST (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, FPS");	values.put(COL_RELEASE, "2009-09-22");	values.put(COL_BLURB, "Halo 3: ODST returns players to familiar ground on a vital, top-secret mission. The gripping story, cooperative campaign and new multiplayer content will have Halo fans 'Preparing to Drop' in Fall 2009. Originally titled Halo 3: Recon, the new game brings the perspective of new characters to the Human-Covenant struggle, as it explores the ODST, or Orbital Drop Shock Troopers. Follow the story of the legendary ODSTs or Orbital Drop Shock Troopers as they drop into the ruined city of New Mombasa, looking for clues behind the Covenant's catastrophic attack on the city. Prepare to drop. Known for their courage, valor and at times, insanity, Orbital Drop Shock Troopers are among the fiercest UNSC soldiers, priding themselves on being the first unit deployed into hostile situations. While not as large or supernaturally gifted as their Spartan comrades, these Hell Jumpers more than compensate with their ferocious attitudes and unwavering nerve. All the traditional features of Halo 3 multiplayer will be included in the new game, including full-featured integration with the Forge map editor.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Halo 4 (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, FPS");	values.put(COL_RELEASE, "2012-11-06");	values.put(COL_BLURB, "The Master Chief returns to battle an ancient evil bent on vengeance and annihilation. Shipwrecked on a mysterious world, faced with new enemies and deadly technology, the universe will never be the same. Enlist aboard the UNSC Infinity to experience Halo's original multiplayer and Spartan Ops - episodic fiction-based co-op missions.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Halo Reach (Xbox 360)");	values.put(COL_GENRE, "Action, Shooter, FPS");	values.put(COL_RELEASE, "2010-09-14");	values.put(COL_BLURB, "Before the Covenant was defeated on Earth, before all humanity could be saved, an epic battle took place for Planet Reach that would change the course of history. The first chapter chronicling the epic story of our survival is finally here. Join Noble Team on a crucial mission through our darkest hours to ensure the continuation of the human race. With the courage and sacrifice of a Spartan, it's up to you to make sure humanity's first stand is not our last. In Halo: Reach, the blockbuster prequel to the Halo trilogy, experience the events that transpired on the planet Reach. Created by acclaimed developer Bungie, Halo: Reach was released in the fall of 2010 exclusively on Xbox 360. As a bonus for Halo fans, Halo 3: ODST will be the key to entry for the Halo: Reach multiplayer beta coming to Xbox LIVE.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Halo 5 Gaurdians (Xbox One)");	values.put(COL_GENRE, "Action, Shooter, MOBA, FPS");	values.put(COL_RELEASE, "2015-10-27");	values.put(COL_BLURB, "Peace is shattered when colony worlds are unexpectedly attacked. But when humanity's greatest hero goes missing, a new Spartan is tasked with hunting the Master Chief and solving a mystery that threatens the entire galaxy.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Hellgate London (PC)");	values.put(COL_GENRE, "Action, Sci-fi, RPG, FPS");	values.put(COL_RELEASE, "2007-10-30");	values.put(COL_BLURB, "Hellgate: London combines the depth of role-playing games with the action of first-person action titles. It is a world devastated by a demon invasion, where players must create a hero and battle through innumerable hordes of demons while completing quests and advancing through experience levels. Explore a desolate city scorched by hellfire where the survivors meld science and sorcery to gain a foothold against the minions of darkness and save the bloodline of humanity. A robust, flexible skill and spell system, highly customizable items, and a massive variety of randomly generated equipment allow players to create heroes that are truly unique. Compelling cooperative multiplayer experience - by creating unique and individualized game play instances within a vast online community, gamers get all the best parts of traditional massive multiplayer games.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of Might and Magic III (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "1999-02-28");	values.put(COL_BLURB, "In this turn-based strategy game you combine the use of strategy, magic and brute force. Venture your way to other towns, interact/fight with other heroes and even cross into the subterranean world to deal with the dregs of humanity (or in this case, the undead). Ship-to-ship combat is another element of the fighting skills you will have to master in order to succeed. You are depended upon to restore honor to a fallen kingdom and re-establish its dominance.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of Might and Magic IV (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2002-03-28");	values.put(COL_BLURB, "Heroes of Might and Magic IV challenges your tactical skills and tests your cunning. Enter a new world of brave heroes and powerful creatures and lead them in combat. Fight your enemies, capture towns, and collect vital resources and artifacts. All-new graphics and gameplay increase the challenge and the make the game more exciting than ever, as you fight to rule a world!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of Might and Magic V Tribes of the East (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2007-10-19");	values.put(COL_BLURB, "Tribes of the East is the second stand-alone expansion pack for Heroes of Might and Magic V once again set in Ashan World but now bringing the Stronghold faction with orcs to the table and an additional upgrade to all dwellings. The first mission introduces the orcs, followed by 3 full campaigns for the Necropolis, Academy and Stronghold faction, with 5 missions each and all linking a single storyline. There are also improvements to the gameplay itself, bugfixes, and a revision of the combat interface and a refined map editor. Other changes include new and easier access to spells, and settings for in-game and combat modes, providing additional information about the minions. The new Stronghold faction offers 7 units (Centaur, Cyclops, Goblin, Shaman, Slayer, Warrior and Wyvern), the racial skill Blood Rage and the Barbarian as a hero.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of Might and Magic VI (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2011-10-13");	values.put(COL_BLURB, "The adventure in Heroes VI, starting 400 years before events in Heroes V, catapults a family of heroes into a fast-paced epic story where Angels plot to end -- once and for all -- an unfinished war with their ancient rivals, the Faceless. A legendary Archangel General is resurrected, but with his powers crippled. Plagued by horrible memories of the Elder Wars, he plots to recover his powers and take control of Ashan while destroying both Faceless and Demons in a series of carefully orchestrated attacks and betrayals. He underestimates, however, the power of the all-too-human Griffin dynasty. The destiny of these Griffin heroes will be determined by our players.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of Might and Magic VII (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, Turn-based, TBS");	values.put(COL_RELEASE, "2015-09-29");	values.put(COL_BLURB, "Our story takes place during a war of succession. The Empress murder has left a realm in flames with many hungry rivals ready to seize the throne by force. The Duke Ivan then calls together a prestigious council of six trusted advisors to restore order and end the conflict that set ablaze Ashan's lands. Might & Magic Heroes VII makes a triumphant return bringing you the essence of turn based strategy gaming. Set in a fantasy universe with RPG progression with a strong story narrative, you will embark on a journey that you will never forget!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Heroes of the Storm (PC)");	values.put(COL_GENRE, "Strategy, MOBA, Arena");	values.put(COL_RELEASE, "2015-06-01");	values.put(COL_BLURB, "Wage war with the most powerful heroes from Blizzard Entertainment's game universes in the explosive multiplayer game Heroes of the Storm, based on the classic and hugely influential Defense of the Ancients game MOD. Heroes of the Storm is a team-based competitive game in which each player controls a powerful hero with unique abilities, and works with his or her team to invade and destroy the enemy team's base.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Killing Floor (PC)");	values.put(COL_GENRE, "Action, Shooter, Horror, FPS");	values.put(COL_RELEASE, "2009-05-14");	values.put(COL_BLURB, "Killing Floor is a Co-op Survival Horror FPS set in the devastated cities and countryside of England after a series of cloning experiments for the military goes horribly wrong. You and your friends are members of the military dropped into these locations with a simple mission: Survive long enough to cleanse the area of the failed experiments!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Kingdoms of Amalur Reckoning (Xbox 360)");	values.put(COL_GENRE, "Action, Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2011-09-30");	values.put(COL_BLURB, "Kingdoms of Amalur: Reckoning is a single-player RPG that sets players on a heroic journey to unlock the mysteries of Amalur, a mysterious and magical new fantasy world created by New York Times best-selling author R. A. Salvatore.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Mass Effect (Xbox 360)");	values.put(COL_GENRE, "Sci-fi, RPG, Third-person, TPS");	values.put(COL_RELEASE, "2007-09-03");	values.put(COL_BLURB, "Set 200 years in the future in an epic universe, Mass Effect places gamers in a vast galactic community in danger of being conquered by a legendary agent gone rogue. A spectacular new vision from legendary developers BioWare, Mass Effect challenges players to lead a squad of freedom fighters as they struggle against threatening armies to restore peace in the land. Mass Effect is the first in a trilogy of games with an overarching story. As the first human Specter  sworn defenders of galactic peace  your mission is to halt the advancing armies of a legendary agent gone rogue. But as you lead your elite team across hostile alien worlds, you will discover the true threat is far greater than anyone imagined.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Mass Effect 2 (Xbox 360)");	values.put(COL_GENRE, "Sci-fi, RPG, Third-person, TPS");	values.put(COL_RELEASE, "2010-01-13");	values.put(COL_BLURB, "Conceived as a trilogy, the sequel to Mass Effect promises another epic intergalactic tale of planetary exploration, civil conflict, challenges of conscious, and perhaps even romantic entanglements. In this dark second chapter, Saren's evil army of Geth soldiers has just been defeated, and humans, who are still struggling to make their mark on the galactic stage, are now faced with an even greater peril.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Mass Effect 3 (Xbox 360)");	values.put(COL_GENRE, "Sci-fi, RPG, Third-person, TPS");	values.put(COL_RELEASE, "2012-03-06");	values.put(COL_BLURB, "In Mass Effect 3, an ancient alien race known only as Reapers, has launched an all-out invasion of the galaxy, leaving nothing but a trail of destruction in their wake. Earth has been taken, the galaxy is on the verge of total annihilation, and you are the only one who can stop them. The price of failure is extinction. You, as Commander Shepard, must lead the counter assault to take it back. Only you can determine how events will play out, which planets you will save from annihilation and which alliances you will form or abandon as you rally the forces of the galaxy to eliminate the Reaper threat once and for all. Battle with your comrades or even your own friends in this all-out galactic war to take Earth back. With co-op online multiplayer missions new to the Mass Effect universe , you can choose from a variety of classes and races, form an elite Special Forces squad, and combine weapons, powers and abilities to devastating effect as you all fight together to liberate key territories from enemy control in this third entry of the epic intergalactic RPG franchise.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Middle Earth Shadow of Mordor (PC)");	values.put(COL_GENRE, "Fantasy, RPG, Third-person");	values.put(COL_RELEASE, "2014-09-30");	values.put(COL_BLURB, "You are Talion, a Ranger of the Black Gate, keeping watch over Mordor which has remained undisturbed for ages. In the blink of an eye, everything is taken from you - your friends, your family, and even your own life. Resurrected by a vengeful spirit, you must now embark on a relentless vendetta against those who have wronged you. Fight through Mordor and uncover the truth of the spirit that compels you, discover the origins of the Rings of Power, build your legend and ultimately confront the evil of Sauron in this new chronicle in Middle-earth.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Payday 2 (PC)");	values.put(COL_GENRE, "Action, Shooter, Modern, FPS");	values.put(COL_RELEASE, "2013-08-13");	values.put(COL_BLURB, "PAYDAY 2 is an action-packed, four-player co-op shooter that once again lets gamers don the masks of the original PAYDAY crew - Dallas, Hoxton, Wolf and Chains - as they descend on Washington DC for an epic crime spree. The new CRIMENET network offers a huge range of dynamic contracts, and players are free to choose anything from small-time convenience store hits or kidnappings, to big league cyber-crime or emptying out major bank vaults for that epic PAYDAY. While in DC, why not participate in the local community, and run a few political errands? Up to four friends co-operate on the hits, and as the crew progresses the jobs become bigger, better and more rewarding. Along with earning more money and becoming a legendary criminal comes a new character customization and crafting system that lets crews build and customize their own guns and gear.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Puzzle Quest Challenge of the Warlords (XBLA)");	values.put(COL_GENRE, "Fantasy, Strategy, Puzzle, Turn-based, TBS");	values.put(COL_RELEASE, "2007-03-20");	values.put(COL_BLURB, "Puzzle Quest: Challenge of the Warlordsâ„¢ delivers, for the first time ever, classic puzzle-game action backed with an epic story of good versus evil. Challenge your puzzle skills in single-player campaign mode, or battle your friends in multiplayer action. Experience a puzzle game with role-playing elements. It's like nothing you've played before.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Puzzle Quest 2 (XBLA)");	values.put(COL_GENRE, "Fantasy, Strategy, Puzzle, Turn-based, TBS");	values.put(COL_RELEASE, "2010-06-22");	values.put(COL_BLURB, "Escape to a puzzle game fantasy world filled with amazing creatures, powerful weapons, and challenging minigames! Addicting Match 3 gameplay is blended seamlessly with immersive role playing in this sequel to the award-winning Puzzle Quest! Jump right into the action and customize your character with any one of four classes, each with different skills and abilities. Gain experience and earn treasure as you progress through the adventure, unlocking new spells and harder Match 3 challenges! Are you a brave enough hero to reclaim the once peaceful village of Verloren from the evil clutches of the demon Gorgon?");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Quake 3 Arena (PC)");	values.put(COL_GENRE, "Action, Arena, Shooter, FPS");	values.put(COL_RELEASE, "1999-12-02");	values.put(COL_BLURB, "No one is safe, you must fight your finished! Encounter arenas rife with deathtraps, hazards and ruthless foes who play with your already twitching mind. Lunge onto a state of harrowing landscapes and a veiled abyss.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Recettear An Item Shop's Tale (PC)");	values.put(COL_GENRE, "Fantasy, RPG");	values.put(COL_RELEASE, "2010-09-10");	values.put(COL_BLURB, "Recettear is the story of an item shop, the girl who lives in it, and the fairy who turned her life upside down. Recette Lemongrass finds herself in charge of an item shop built into her house, in order to pay back a loan her father took and then skipped out on - and Tear, her newfound fairy 'companion', won't take no for an answer! As Recette, you have to decide how you'll get your stock - either through playing the markets in town or going out into the wild with an adventuring friend and thrashing beasts until they give up the goodies - how much to sell things for, what the shop should look like, and how to best go about getting the money Tear needs to pay off the loan. If you can't come up with the money... well, hope you like living in a cardboard box.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "SimCity (PC)");	values.put(COL_GENRE, "Strategy");	values.put(COL_RELEASE, "2013-03-05");	values.put(COL_BLURB, "The defining city simulation is back! Create the city you desire and make the choices that shape your city and power the Sims within it. Every decision, big or small, has real consequences. Invest in heavy industry and your economy will soar - but at the expense of your Sims' health as pollution spreads. Implement green technology and improve your Sims' lives while risking higher taxes and unemployment. Team up with your friends to solve global challenges: launch a space shuttle, reduce carbon emissions, or build magnificent wonders. Compete on global and regional leaderboards to be the richest, the dirtiest, the happiest or the best place to visit!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Soulcalibur IV (Xbox 360)");	values.put(COL_GENRE, "Action, Fighting");	values.put(COL_RELEASE, "2008-07-29");	values.put(COL_BLURB, "From Namco's acclaimed weapon-based fighting series comes the fourth chapter in the series (and first for Xbox 360 and PlayStation 3). Delivering new gameplay modes, characters and enhanced features with unprecedented 3D modeling and animation, Soulcalibur IV aims to be a definitive fighting game experience.<br /><br />Set to finally reveal the origins of the Soulcalibur saga, the game features both new and familiar faces from across the galaxy who seeks the rival swords for their own goals. Continuing the tradition of breaking new boundaries, legendary Star Wars icons Darth Vader and Yoda invade the Soulcalibur universe to add a new layer of depth, challenge, and mystery. Also for the first time in the franchise, customized characters or original favorites can be taken online to challenge others for the top spot of this timeless series.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "SPAZ Space Pirates and Zombies (PC)");	values.put(COL_GENRE, "Strategy, Sci-fi");	values.put(COL_RELEASE, "2011-08-15");	values.put(COL_BLURB, "Space Pirates and Zombies takes place far enough in the future that Earth has become a toxic backwater planet. The galaxy has been colonized by humans, and the only means to travel to new star systems is through highly restricted and well defended warp gates. It is well known that systems closer to the galactic core become richer and richer as well as more scientifically advanced. This has led to theories of a secret system with a cache of treasure or knowledge at the galactic core feeding this growth. As a pirate, you must assemble a fleet and discover what treasure awaits you there. Space Pirates and Zombies is a mix of the deep old school space adventure genre with modern physics, action and graphics technology.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Starcraft 2 (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS");	values.put(COL_RELEASE, "2010-07-27");	values.put(COL_BLURB, "The original StarCraft made its debut in 1998, and it quickly became one of the most popular real-time strategy games of all time. We've waited a long time for an updated sequel, and rumors of it were periodically dangled in front of us like a space carrot over the years. So why did it take so long? Because that is precisely how long it took to fill it with the perfect amount of awesome. It's a continuation of the epic struggle between the human Terrans, the insect-like Zerg and the psionic Protoss. Fans of the original will see some familiar faces, as well as a cast of new heroes as they do battle across the galaxy with veteran, upgraded and brand new unit types. To remain consistent with the game's new-millennium feel, the Battle.net gaming service has been completely revamped to offer noticeable enhancements and new features in multiplayer mode. The fun of StarCraft II is not limited to those who played the first StarCraft, however. Even if you were a toddler when the first game came out, you'll be able to choose your faction and jump right into the fray.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Tabula Rasa (PC)");	values.put(COL_GENRE, "MMO, RPG, Sci-fi, Third-person");	values.put(COL_RELEASE, "2007-11-02");	values.put(COL_BLURB, "Tabula Rasaâ„¢ is a massively multiplayer online action game that takes you into the heat of battle at the frontlines of an epic war between a xenophobic alien race bent on galactic conquest and the coalition of rebel soldiers who've traveled across the galaxy to stop them. Developed with the legendary Richard Garriott.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Terraria (PC)");	values.put(COL_GENRE, "Fantasy, RPG, Sandbox");	values.put(COL_RELEASE, "2011-05-16");	values.put(COL_BLURB, "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. The world is your canvas and the ground itself is your paint. Grab your tools and go! Make weapons to fight off a variety of enemies in numerous biomes. Dig deep underground to find accessories, money, and other useful things. Gather resources to create everything you need to make the world your own. Build a house, a fort, or even a castle. People will move in to live there and perhaps even sell you different wares to assist you on your journey. But beware, there are even more challenges awaiting you... Are you up to the task?");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "The Lord of the Rings The Battle for Middle Earth (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, RTS");	values.put(COL_RELEASE, "2004-12-06");	values.put(COL_BLURB, "The Lord of the Rings: The Battle for Middle-Earth is an epic campaigns where the goal is to control all of Middle-Earth! Wage all-out combat against either the forces of good or the armies of evil, controlling troops and managing resources. The fate of a continent is your hands! The game retains the basic mechanics of real-time strategies. Warring factions gather resources, then use them to construct military bases and armies on-site. In Battle for Middle-Earth, buildings may only be constructed on the building slots of predefined plots. Plots range from farmhouses to full-fledged castles, with different slot arrangements and available buildings, and plots can be purchased when they're in the sole presence of a side's forces. The only resource are the nebulous 'resources,' which are produced inexhaustibly in dedicated buildings.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "The Lord of the Rings The Battle for Middle Earth 2 (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, RTS");	values.put(COL_RELEASE, "2006-03-02");	values.put(COL_BLURB, "Lord of the Rings: The Battle for Middle-Earth II gives you a chance to experience all that Middle-Earth was meant to be. Delve deeper than ever before into the fictional world of Tolkien, as you wage war in the North. Assume command of the most storied civilizations in all of Middle-earth history, the Elven and Dwarven armies -- or if you prefer, fight on the side of Evil to aid Sauron in his conquest. Fight with or against heroes and creatures that have never been seen in The Lord of the Rings films! Control battles with all-new enemy AI, melee combat, and unprecedented tactical fidelity. Build anywhere brings creativity and strategy to base building and battlefield dominance Control the entire war with a high level Risk style meta-game.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "The Secret World (PC)");	values.put(COL_GENRE, "MMO, RPG, Modern");	values.put(COL_RELEASE, "2012-07-03");	values.put(COL_BLURB, "A massively multiplayer online roleplaying game, The Secret World takes place on our earth, in our times, and yet is a tale of mythology and ancient mysteries. For there really is a world within ours, a secret world, where magic exists, monsters roam and ancient forces are fighting for the dominance of earth. It is a world of legendary stories, ageless conflicts and powerful cabals. In this world, even modern cities hide secrets. In this world, players can take part in the greatest conspiracies of our age, and battle the forces of darkness across the world and throughout time.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Tom Clancy's The Division (PC)");	values.put(COL_GENRE, "Action, RPG, Modern, Third-person, TPS");	values.put(COL_RELEASE, "2016-03-07");	values.put(COL_BLURB, "We live in a complex world. The more advanced it gets, the more vulnerable it becomes. We've created a house of cards: remove just one, and everything falls apart. Black Friday  a devastating pandemic sweeps through New York City, and one by one, basic services fail. In only days, without food or water, society collapses into chaos. The Division, an autonomous unit of tactical agents, is activated. Leading seemingly ordinary lives among us, these agents are trained to operate independently in order to save society. When society falls, we rise.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Too Human (Xbox 360)");	values.put(COL_GENRE, "Sci-fi, Action, RPG");	values.put(COL_RELEASE, "2008-08-19");	values.put(COL_BLURB, "Too Human is a third-person action adventure role-playing game like Champions of Norrath. It features twitch gameplay in the form of fast-paced melee and ranged combat while also maintaining RPG elements including skill tree progression and dungeon crawling. As a third-person action adventure game, Too Human features two notable features which are melee combat being controlled dynamically off the right analogue stick and a camera system that is controlled by AI. The right analogue stick controlled combat removes the issues of three dimensional depth perception during combat while the AI controlled camera system allows for a cinematic experience while also being an aid to the story telling. The RPG elements of Too Human include its story, different selectable classes, customizable weapons, armor and cybernetics, skill tree progression and item hunting. Too Human has 15 different weapon classes, including two-handed swords, hammers, polearms, pistols, rifles, lasers, dual-wielded one-handed swords and staves. The character is able to customize their armor in terms of color and its effectiveness against certain forms of attacks while also being able to swap armor sets. This game features skill trees unique to all the various classes that can be customized to the player's liking, this combined with the fact that it also includes item hunting like Diablo greatly increases the replayability of Too Human.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Torchlight (Xbox 360)");	values.put(COL_GENRE, "Fantasy, Action, RPG, Isometric");	values.put(COL_RELEASE, "2009-10-27");	values.put(COL_BLURB, "Players will choose from among three character classes, and venture from the safety of the town of Torchlight into randomly generated dungeon levels, with a huge variety of creepy monsters, endless variations of loot to find, and quests to complete. The endless randomization ensures a long-lived gameplay experience. Randomization - Our level layouts are randomly created, so each adventure is unique. Monsters, treasures, puzzles, and items are also different each time you embark on an adventure. Easy, approachable interface - Torchlight is designed to be easy to play right from the beginning. The intuitive interface gives players easy access to a rich and varied world. Retirement System - Once characters are sufficiently leveled up, they can â€œretireâ€ and bestow specific benefits and perks to new characters. Pets - Players will choose a pet to accompany them. Pets can level up along with the player, and will help in battle, carry items, and perform a variety of helpful services. Character Classes - Players will create and customize a character from one of three classes available, and choose an animal companion. Through cosmetic choices, skill path decisions, and the treasures they acquire, each character will be custom-tailored and different. Fishing - Players can take a break from the high-energy pace of adventuring to visit one of the fishing holes and relax and see what they can catch. Fish have interesting benefits for the player and pet, and other rewards can also be discovered. Included Editor - Runic Games is embracing our modding community by including an editor so our players can create and design their own content.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Torchlight 2 (PC)");	values.put(COL_GENRE, "Fantasy, Action, RPG, Isometric");	values.put(COL_RELEASE, "2009-10-27");	values.put(COL_BLURB, "The award-winning action RPG is back, bigger and better than ever! Torchlight II takes you back into the quirky, fast-paced world of bloodthirsty monsters, bountiful treasures, and sinister secrets - and, once again, the fate of the world is in your hands! Torchlight II captures all the flavor and excitement of the original game - while expanding the world and adding the features players wanted most, including online and LAN co-op multiplayer. Torchlight II is fast, fun, and filled to the brim with action and loot. Adventure solo or online with your friends!");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Total Annihilation (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS");	values.put(COL_RELEASE, "1997-10-25");	values.put(COL_BLURB, "What began as a conflict over the transfer of consciousness from flesh to machines escalated into a war which has decimated a million worlds. The Core and the Arm have all but exhausted the resources of a galaxy in their struggle for domination. Both sides now crippled beyond repair, the remnants of their armies continue to battle on ravaged planets, their hatred fuelled by over four thousand years of total war. This is a fight to the death. For each side, the only acceptable outcome is the complete elimination of the other.In the distant future, the galaxy is ruled by a central body of humans and artificial intelligences called the Core (a contraction of 'Consciousness Repository'). The Core's technological and economic triumphs have allowed humanity to colonize most of the Milky Way and enjoy peace and prosperity. However, the balance is broken by a technological breakthrough that allows the consciousness of a human being to be reliably transferred into a machine, thereby theoretically granting infinite life, in a process called 'patterning.' Following a mandate imposed on humanity by the Core requiring everyone to undergo patterning as a public health measure, a rebel band is formed out of colonies from the edges of the galaxy (hence their name, the Arm), whose members refused to leave their natural bodies to join the Core's machines. A war lasting 4,000 years followed, with the Arm mass-producing clones as pilots for its vehicles and the Core duplicating consciousness-embedded microchips to pilot its own machines. Total Annihilation (TA) is a real-time strategy (RTS) video game created by Cavedog Entertainment under the guidance of lead designer Chris Taylor. It was released on September 30, 1997, and was the first RTS game to feature 3D units and terrain. Two expansion packs were released: The Core Contingency on April 30, 1998, and Battle Tactics exactly 2 months later on June 30, 1998. When TA was released, the minimum computer requirements were a Pentium 100 MHz processor and 16 MB of RAM. Of course, these requirements were for computers in 1997; modern day machines easily exceed those recommended specifications, but it is still recommended to have a 1 GHz processor and 512 MB of RAM for the updated game engine.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Unreal Tournament 2004 (PC)");	values.put(COL_GENRE, "Sci-fi, Action, Arena, Shooter, FPS");	values.put(COL_RELEASE, "2004-03-16");	values.put(COL_BLURB, "Epic has taken the core of Unreal Tournament 2003, with its massively improved graphics, new weapons, and huge levels, and added layers and layers of polish and game play depth. Along with all of UT2003's game modes and maps, UT2004 will be released with vehicles, new weapons, two new game modes, and more new maps. The popular Assault mode from the original Unreal Tournament makes a welcome return to the series. The game mechanics remain the same: one team attacks by completing a series of objectives, while the other team must prevent them from succeeding. The new Onslaught mode is best described as connect-the-dots, where players compete to take over neutral nodes and establish bases in strategic locations.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Unreal Tournament 3 (PC)");	values.put(COL_GENRE, "Sci-fi, Action, Arena, Shooter, FPS");	values.put(COL_RELEASE, "2007-11-03");	values.put(COL_BLURB, "The Necris invasion has begun, and your clan was one of the first to be slaughtered. Head to the front lines and join this Epic battle to defend humanity while taking your revenge. Unreal Tournament 3 marks the return of the premiere tournament-style first-person shooter. Unreal Tournament 3 unleashes the full power of Unreal Engine 3, taking graphics, gameplay, and challenge to a whole new level. Players engage in intense and hyper-real battles with other human players online or against incredibly realistic Unreal artificial intelligence. Over two dozen weapons and vehicles have been upgraded and enhanced for maximum killing potential. Take on all comers in a variety of game modes including Deathmatch, Team Deathmatch, Capture the Flag, an all-new Warfare mode and more.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warcraft 3 Reign of Chaos (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, RTS");	values.put(COL_RELEASE, "2002-07-02");	values.put(COL_BLURB, "Warcraft III: Reign Of Chaos is an impressive real time strategy game where you build, attack & destroy in a darker world. Visit the interactive 3D fantasy world of Azeroth, setting of the first two Warcraft games. It is 15 years after the war between humans and orcs. While mankind grew soft and complacent, the orcs were regrouping. The drums of war are beating again -- the Burning legion is coming and with it they bring terror and destruction. Do what you must to stop the death of your world.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warcraft 3 The Frozen Throne (PC)");	values.put(COL_GENRE, "Fantasy, Strategy, RTS");	values.put(COL_RELEASE, "2003-07-01");	values.put(COL_BLURB, "Experience the next chapter in the Warcraft Saga! Warcraft III: The Frozen Throne is the official expansion pack to Warcraft III: Reign of Chaos. Many months have passed since Archimonde and the Burning Legion were defeated at the Battle of Mount Hyjal. For each race, The Frozen Throne adds several new units and buildings, including a player-controlled shop, and one new hero per race. The population limit has been increased from 90 to 100. In addition, The Frozen Throne re-introduces naval battles, which were almost completely absent in Warcraft 3. Although generally only available in the campaign, naval units can be placed using the World Editor and can be purchased from certain buildings in melee maps.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warframe (PC)");	values.put(COL_GENRE, "Sci-fi, Action, MMO, Third-person, TPS");	values.put(COL_RELEASE, "2013-05-25");	values.put(COL_BLURB, "Warframe is a cooperative free-to-play online action game set in an evolving sci-fi world. Join your friends in player-vs-enemy raids across the solar system and master the power of the Warframes. Stand alone or fight together against enemies that threaten your world.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Dawn of War Dark Crusade (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS, WH40k");	values.put(COL_RELEASE, "2006-10-09");	values.put(COL_BLURB, "Warhammer 40,000: Dawn of War - Dark Crusade features two new playable races, the Tau Empire and the Necrons, bringing the number of totally unique races to an unprecedented seven. In addition to the two new playable races, Dark Crusade will feature an all-new single player campaign centering on the conquest of a 'meta-map,' with each territory captured giving tangible rewards to the occupying force. A greatly expanded multiplayer component and a completely unique economy model for the Necrons will present gamers with the most compelling Dawn of War game to-date. Customize and manage a persistent army as you sweep across the planet. Customize the appearance and abilities of your commander unit as he grows in power and influence. Discover the dark secrets of a planet shrouded in mystery.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Dawn of War Soulstorm (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS, WH40k");	values.put(COL_RELEASE, "2008-03-05");	values.put(COL_BLURB, "Soulstorm takes its name from the strange events in the area the game takes place in. A warp storm surrounds a planetary system and isolates it from all forms of contact. The nine factions drawn to investigate arrive in the system with their own fleets, and their own conflicting intentions. But the warp storm wreaks havoc with their navigational systems and strands them on the four planets and three moons of the system. The nine factions are then forced to battle between planets to ultimately conquer the planetary system and discover the reason for the warp storm. There are 31 territories, over four planets (and moons).");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Dawn of War 2 (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS, Squad, WH40k");	values.put(COL_RELEASE, "2009-02-19");	values.put(COL_BLURB, "It's the 41st Millennium in the Sub-Sector Aurelia a cluster of worlds on the edge of the Galaxy where a battle of epic proportions is about to commence. Ancient races will clash across the planets that dot this section of space, battling for the greatest of stakes not only the claim to the land and its bounty - but the fate of each race. Dawn of War II ushers in a new chapter in the acclaimed RTS series taking players to the brutal frontlines of war to lead an Elite Strike Force on a mission to save the galaxy. With a focus on fast-action RTS gameplay, Dawn of War II brings to life the science fiction universe of Warhammer 40,000 like never before. Experience the intimate brutality of battle as you play through your chosen race's epic campaign. Clash with enemies on battlefields ablaze with visceral melee and ranged combat. Lead and develop your squads from raw recruits into the most battle hardened veterans in the Galaxy.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Dawn of War 2 Chaos Rising (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS, Squad, WH40k");	values.put(COL_RELEASE, "2010-03-11");	values.put(COL_BLURB, "Your Blood Ravens have saved the sector, but can they save themselves? In THQ Inc. and Relic Entertainment's sequel to the acclaimed Dawn of War II real time strategy franchise, you return to sub sector Aurelia where a long lost frozen ice planet has reappeared from the Warp, bringing with it new secrets to uncover and foes to face. In Dawn of War II: Chaos Rising you will take command of the Blood Ravens and defend the sector against the Chaos Space Marines of the Black Legion. Purge the chaos filth and hold the chapter together as traitorous forces work from within to try bring down the Blood Ravens. Upgrade your squads with new legendary wargear and unlock new special abilities, as your squads advance to level 30. Will you remain steadfast to the Emperor or risk heresy to gain new dark and destructive powers? In multiplayer swear loyalty to the Chaos Gods and pit your bloodthirsty warband of Chaos Space Marines against the new units and reinforced armies of the Space Marines, Orks, Eldar, and Tyranids.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Dawn of War 2 Retribution (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, RTS, Squad, WH40k");	values.put(COL_RELEASE, "2011-03-01");	values.put(COL_BLURB, "Taking place years after the events in Dawn of War II: Chaos Rising, this title allows players to choose their perspective with the first multiple-race single player campaign in the Dawn of War II series. Choose your race and determine the final fate of the entire sector in Dawn of War II: Retribution, the next installment in the critically acclaimed Dawn of War real-time strategy franchise.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Warhammer 40000 Space Marine (PC)");	values.put(COL_GENRE, "Sci-fi, Action, Third-person, TPS, WH40k");	values.put(COL_RELEASE, "2011-09-06");	values.put(COL_BLURB, "In Warhammer 40,000: Space Marine you are Captain Titus of the Ultramarines, humanity's last hope for survival in a war-ridden future. Step into the armor of this superhuman warrior and use a lethal combination of deadly weapons to crush overwhelming alien forces. Fight against the savage Orks and the unholy forces of Chaos in a brutally violent world based on the richest science fiction fantasy ever created. Space Marine features a fluid combat system that allows players to seamlessly switch from ranged to melee weapons without interrupting the flow of combat. Hitting the melee button at any time will result in a close range strike with the equipped hand-to-hand weapon as well as the camera pulling out to melee distance. Pulling either trigger will instantly snap the view back to behind the player's shoulder ready for precise shooting. These systems are immediately responsive and leave the player in full control at all times. As the player dispatches enemies in Space Marine they will be earning 'Fury' which can be used to unleash devastating ranged or melee attacks.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "World of Warcraft (PC)");	values.put(COL_GENRE, "Fantasy, MMO, RPG, Terrible, Bad, Horrible, Ugly");	values.put(COL_RELEASE, "2004-11-23");	values.put(COL_BLURB, "IT. JUST. IS.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "Worms Armageddon (PC)");	values.put(COL_GENRE, "Strategy, Humor, Turn-based, TBS, Squad");	values.put(COL_RELEASE, "1999-06-24");	values.put(COL_BLURB, "This action-packed, laugh-filled game takes the popular Worms 2 to the next level. You lead a pack of heavily armed worms into action. Sheep explode, mad cows fall from the sky, old ladies detonate spontaneously--you get the general idea.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "XMen Legends 2 Rise of Apocalypse (PC)");	values.put(COL_GENRE, "Action, RPG, Isometric");	values.put(COL_RELEASE, "2005-09-20");	values.put(COL_BLURB, "Sequel to best-selling X-Men Game / The X-Men and the hated Brotherhood ally in a fight to reclaim Earth from Apocalypse's grasp IIntense online and offline multiplayer action");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "XCOM Enemy Unknown (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, Turn-based, TBS, Squad");	values.put(COL_RELEASE, "2012-10-08");	values.put(COL_BLURB, "XCOM: Enemy Unknown will place you in control of a secret paramilitary organization called XCOM. As the XCOM commander, you will defend against a terrifying global alien invasion by managing resources, advancing technologies, and overseeing combat strategies and individual unit tactics. The original X-COM is widely regarded as one of the best games ever made and has now been re-imagined by the strategy experts at Firaxis Games. XCOM: Enemy Unknown will expand on that legacy with an entirely new invasion story, enemies and technologies to fight aliens and defend Earth. You will control the fate of the human race through researching alien technologies, creating and managing a fully operational base, planning combat missions and controlling soldier movement in battle.");	db.insert(GAME_TBL_NAME, null, values);
        values = new ContentValues(); values.put(COL_NAME, "XCOM 2 (PC)");	values.put(COL_GENRE, "Sci-fi, Strategy, Turn-based, TBS, Squad");	values.put(COL_RELEASE, "2016-02-05");	values.put(COL_BLURB, "XCOM 2 is the sequel to XCOM: Enemy Unknown, the 2012 award-winning strategy game of the year. Earth has changed. Twenty years have passed since world leaders offered an unconditional surrender to alien forces. XCOM, the planet's last line of defense, was left decimated and scattered. Now, in XCOM 2, the aliens rule Earth, building shining cities that promise a brilliant future for humanity on the surface, while concealing a sinister agenda and eliminating all who dissent from their new order. Only those who live at the edges of the world have a margin of freedom. Here, a force gathers once again to stand up for humanity. Always on the run, and facing impossible odds, the remnant XCOM forces must find a way to ignite a global resistance, and eliminate the alien threat once and for all. ");	db.insert(GAME_TBL_NAME, null, values);
    }
//-------------END HARDCODED #overkill DB SEED---------------\\

    public Cursor listGames(){
        SQLiteDatabase db = this.getReadableDatabase();

        Cursor cursor = db.query(
                GAME_TBL_NAME,
                new String[]{COL_ID, COL_NAME, COL_GENRE, COL_RELEASE, COL_BLURB},
                    null, null, null, null, null);
        return cursor;
    }

    public Cursor searchLibrary(String query){
        SQLiteDatabase db = this.getReadableDatabase();

        Cursor cursor = db.query(
                GAME_TBL_NAME,
                GAME_COLUMNS,
//Commenting out ID and BLURB so that walls of text and random numbers aren't searchable.
                //COL_ID + " LIKE ? OR " +
                COL_NAME + " LIKE ? OR "
                + COL_GENRE + " LIKE ? OR "
                + COL_RELEASE + " LIKE ? ",
                //+ COL_BLURB + " LIKE ?",
                new String[]{
//                        "%" + query + "%",
//                        "%" + query + "%",
                        "%" + query + "%",
                        "%" + query + "%",
                        "%" + query + "%"},
                        null, null, null, null);

        //import android.database.DatabaseUtils; //uncomment, append to top for console debug
        //DatabaseUtils.dumpCursor(cursor); //uncomment for console debug
        return cursor;
        }

}//end DatabaseHelper
